### ISSUE TITLE
Set position configurations

### ISSUE THREAD

**Issue by thearian** [SinaBYR/analogue.nvim#6]
Awesome plugin you've built pal! I use it everyday and became a feature I love about my neovim setup.
I request a feature about positioning.
The default `Analogue` panel will position itself on top of my `lualine` and gets some info hidden.
It would be great if I could manually move the position permanently (namely at configuration setup).
Thank you for the great plugin!

**Comment by SinaBYR** [comment]
Thanks! it's a great feeling to get feedback for what you work on. I'm currently working on a new custom command named `:AnaloguePositionX` and `:AnaloguePositionY` which basically can be used to adjust the clock position on x-axis and y-axis, respectively. Also sorry for the late reply, been very busy lately.

**Comment by SinaBYR** [comment]
Initial position of the clock has been changed and from now on it will be exactly one line space above lualine by default. [#ef79f84](https://github.com/SinaBYR/analogue.nvim/commit/ef79f843656ef21dc90d99746e10cc9082e80a49)

**Comment by SinaBYR** [comment]
the issue has been resolved not by introducing new commands, but by changing clock's default position.

**Comment by SinaBYR** [comment]
The issue has been resolved not by introducing new commands, but by changing clock's default position.
